### ISSUE TITLE
Add name to header

### ISSUE THREAD

**Issue by MavOmidK** [project-hopkins/Hannibal#24]
Add the name of the user to the header. 
If not logged in, just say Guest.

**Comment by aagavin** [comment]
Would a logo be better?

**Comment by kevinburnside** [comment]
I think he means the users name

**Comment by aagavin** [comment]
Oh ok. Then an avatar?

**Comment by kevinburnside** [comment]
Arron are you are you able to add an avatar image to the backend?  Maybe just like generic one to start and possibly we could have an option to choose which avatar the user wants.

**Comment by aagavin** [comment]
Do you want to store the avatar image in the backed?

Or do want github style images?
